core/src/main/java/it/pagopa/selfcare/mscore/core/EmailService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/MailParametersMapper.java, core/src/test/java/it/pagopa/selfcare/mscore/core/EmailServiceTest.java
1) retrive product name for subject's mail instead of product id
2) retrive product name for body's mail instead of product id  
3) retrive product name for contract name instead of product id  
this fix allows the user to see the product name instead of the product id when receiving the mail after an onboarding
ES. "Firma con IO" instead "prdo-io-sign"
an onboarding request was made and subsequently it was verified that the product name was actually retrieved in the subject and body of the email and in the name of the contract
=> Feature/selc 2424 (#106) - Retrive product name instead product id in subject and body's mail and in contract name 

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/OnboardingControllerTest.java
implementation of the API that allows onboarding without going through the validation phase.
The API is identical to "completeOnboarding" but the validation phase is not performed
this implementation was performed to allow manual onboardings in case of need
In addition to the unit tests implemented, local tests were performed to verify the correct functioning of the API
=> [SELC - 2472] - implemented consume token api

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/InstitutionToNotify.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java
Need to add city, country and county to notification message sent to Data Lake
Needed for SAP to billing requirements
Deployed on dev environment and tested by onboarding an institution and checked if the fields are filled correctly
{
"id":"18971cd9-65c0-4a21-b50f-2d287c13851b",
"internalIstitutionID":"d0d28367-1695-4c50-a260-6fda526e9aab",
"product":"prod-fd",
"state":"ACTIVE",
"filePath":"parties/docs/18971cd9-65c0-4a21-b50f-2d287c13851b/Prod Fideiussioni Digitali_accordo_adesione (2).pdf",
"fileName":"Prod Fideiussioni Digitali_accordo_adesione (2).pdf",
"contentType":"application/pdf",
"onboardingTokenId":"18971cd9-65c0-4a21-b50f-2d287c13851b",
"institution":{
"institutionType":"PA",
"description":"Comune di Milano",
"digitalAddress":"protocollo@postacert.comune.milano.it", …
=> add city, country and county to notification message

core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java
set createdAt if updateAt is null when sending notification
Missing updateAt when sending notification
=> fix: set as createdAt if updateAt is null when sending notification

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
fix search filter for retrieveUserRelationships in InstitutionServiceImpl
Api doesn't filter correctly
try to call https://api.selfcare.pagopa.it/external/party-management/v1/relationships?to=e65fac74-00ae-4c01-b6e9-5f12b37a8165&from=0451314a-92a8-4ef0-9cc6-91025de58b4d&productRoles=admin
=> HotFix - Api GetRelationships non filtra correttamente

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/NotificationToSend.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/Token.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/utils/MockUtils.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/TokenEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/utils/DaoMockUtils.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImplTest.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/TokenMapperTest.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/utils/TestUtils.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingDaoTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/migration/MigrationServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtilsTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TokenUtilsTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/TokenMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/migration/MigrationMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/CrudControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/OnboardingControllerTest.java
Added new Fields to Token Entity; activatedAt and deletedAt
Need to save the instant when a token is consumed and the onboarding is completed and also when a token is regected saving the deletion instant
deployed from branch and verified on DB and eventhub
=> Added activatedAt and deletedAt to Token Entity

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardedInstitutionResponse.java
Added root parent id as attribute of response of onboaring/info api in order to manage this field in ExchangeTokenService
It's necessary to manage this field into dashboard backend 
I have tested the api onboarding/info api locally, aiming to dev environment
=> Added rootParentId into OnboaringInfo response

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/InstitutionPaSubunitType.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/PdfMapperTest.java
Remove set subunitype for EC when saving institution from ipa
Subunitype must be valued only if an institution is AOO or UO
Try to save institution EC and check if subunitType is null
=> feat: remove set subunitype for EC when saving institution from ipa

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/PartyRegistryProxyConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/exception/BadGatewayException.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/exception/ServiceUnavailableException.java, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/decoder/FeignErrorDecoder.java, connector/rest/src/main/resources/config/party-registry-proxy-rest-client.properties, connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImplTest.java, connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/decoder/FeignErrorDecoderTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java
Added FeignErrorDecoder for handling error on proxy client
Added fault tollerance about getting geotax on onboarding
Onboarding must not be fail if geotax is missing
Try to call POST /onboarding/institution with institutionUpdate.geographicTaxonomyCodes wrong (for example "HELLO"), onboarding must be done
=> refactor: handle resource not found when retrieve geotax by proxy

web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/RootParentResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionResourceMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Added rootParent node into InstitutionResponse to wrap all information about EC into specific object
It has been decided to move the construction of this node into microservice and remove from infra's policy.
I have run ms-core microservice locally and test institutions/{id} api and /institutions?taxCode={taxCode}&subunitCode={subunitCode}
=> Added rootParent node into InstitutionResponse

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/UserConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
Added endpoint for delete logically user's association with institution and product
As admin, I want to delete logically user's association with institution and product
Try to call DELETE /users/{userId}/institutions/{institutionId}/products/{productId} on a record where status is ACTIVE
=> feat: added endpoint for delete logically user's association with institution and product

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GetDelegationsMode.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/DelegationInstitution.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/DelegationInstitutionMapper.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/delegation/DelegationResponse.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
Added taxCode and institutionType to getDelegations API
This change was requested by backoffice pagoPA team in order to manage taxCode of institutions retrieved by partner's id
I have tested the api **/delegations** running ms-core microservice locally.
=> Added taxCode and institutionType to getDelegationsAPI

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/Delegation.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/DelegationInstitutionMapper.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/delegation/DelegationResponse.java
Added fields brokerTaxCode and brokerType to DelegationResponse. 
This change was necessary to manage this additional information in case of request populated with institutionId.
I have run ms-core microservice locally and tested the specific API **/delegations** GET
=> Added fields to getDelegations response

connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GenericError.java, connector/email/src/main/java/it/pagopa/selfcare/mscore/connector/email/EmailConnectorImpl.java, connector/email/src/test/java/it/pagopa/selfcare/mscore/connector/email/EmailConnectorImplTest.java
compression of the pdf file in zip format before being attached to the email during the onboarding phase
This modification was necessary because, when the email arrived at the institutions containing the pdf file of the contract, it could happen that the digest of the file was modified by the institutions' protocol system. Compressing the PDF in zip format allows the file itself not to be compromised
- a manual onboarding was carried out and it was verified that the extractable zip archive containing the contract in pdf format had arrived
- Some institutions that had presented the problem described above were selected and the contract was sent to a zip archive. Subsequently, the institutions extracted the contract, digitally signed and uploaded it correctly, completing the onboarding
=> [SELC - 3013] zip archive compression of the pdf file of the contract

app/src/main/resources/swagger/api-docs-v1.json, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java
Updated institution response with fields createdAt and updatedAt.
This change was necessary to give more information about institution to support service.
I have run ms-core microservice locally and tested the api **/institutions?taxCode={taxCode}**
=> Update institution response with fields createdAt and updatedAt

app/src/main/resources/config/azure-storage-config.properties, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/FileStorageConnector.java, connector/azure-storage/src/main/java/it/pagopa/selfcare/mscore/connector/azure_storage/AzureBlobClient.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java
Prod FD has a pdf file as contract, implemented a new method in azure client to retreive the pdf and attach it to the confirmation mail
Prod FD wont use a customizable contract, it has a pdf file that just has to be signed.
Started application locally and did an onboarding procedure and verified the mail
=> add new method in azureBlobClient to retrieve contract as pdf file

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingDaoTest.java
set user product binding status to ACTIVE on manual complete onboardings
Auto complete api sets user binding to TOBEVALIDATED or PENDING state for users that didn't already have an active onbaording on selfcare, this caused the onboarding interceptor to not retrieve the associated users properly breaking the onboarding flow
=> set user product binding status to ACTIVE on manual complete onboardings

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyAnac.java
Changed originId field for ANAC onboarding
In case of onboarding for SA, the field originId is equal to taxCode
=> Changed originId field for ANAC onboarding

app/src/main/resources/config/core-config.properties, connector-api/src/main/java/it/pagopa/selfcare/mscore/config/MailTemplateConfig.java, core/src/main/java/it/pagopa/selfcare/mscore/core/NotificationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/NotificationServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/MailParametersMapper.java, core/src/test/java/it/pagopa/selfcare/mscore/core/NotificationServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/MailParametersMapperTest.java
- added logic to send registration request mail to PT when PT want to onboard on SelfCare
- added logic to send registration notification mail to Admin PagoPA when PT make onboarding request
These new logics have been implemented as if the institution that wants to make an onboarding request is a PT it will not have to sign any contract, the PagoPA admin will simply accept this request and only then will it be able to navigate within the dashboard
Tests were carried out locally. In particular, multiple onboarding requests were made for PT and non-PT institutions in order to verify that the other flow was also working correctly
=> [SELC - 3116] implemented onboarding logic for PT

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingDaoTest.java
added relationShipState ACTIVE for case TOBEVALIDATED
The current flow does not allow the PagoPA admin to approve the request. This is the only case where you switch from TOBEVALIDATED to ACTIVE, so this change is necessary
Local tests have been carried out and requests have been approved in TOBEVALIDATED status
=> fix: added relationShipState ACTIVE for case TOBEVALIDATE

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java
Added check on instutiton identifier to avoid update of status on previous onboarded product.
This fix was made because the introduction of the new user onboarding API had a bug:
- when a user was registered for a product "X" on an institution "X" if the same user had another onboarding on the same product "X" but institution "Y" it was eliminated
I have run microservice locally and test the api for user onboarding.
=> [SELC-3248] bug: added new institutionId check for user binding

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingDaoTest.java
the logic has been added in the method shared between the APIs used to onboard a user on the frontend side and via direct call
This change was necessary because when a frontend user added another user with the OPERATOR role, if this user was already registered as an operator but with a different productRole it was eliminated
the API call was made locally trying to cover all the cases, the unit tests were implemented
=> [SELC - 3099] fix: implemented new logic for onboarding user

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPda.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/CreateInstitutionStrategyFactory.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/PdaInstitutionRequest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerPdaTest.java
Renamed input attribute in request body for API /institutions/from-pda  
Old attribute name was wrong
Local environment
=> fix renamed attribute for SELC-3291

connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GenericError.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyInfocamere.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/CreateInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Added API institution/from-infocamere/ and relative institution strategy to create institution with origin infocamere
We needed this new API to handle correctly the flow of institution creation from infocamere. This API sets the origin INFOCAMERE if can find a legal address on the registry, otherwise it allows to set origin to the caller.
=> SELC-3256 Added API institution/from-infocamere/

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/InstitutionConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GenericError.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyCommon.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPda.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPdaTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
In getInstitutions API added check to perform different queries based on presence of taxCode or origin informations
The previous logic, in an attempt to include more filter possibilities, did not use null-valued fields in the query. Now the queries also contemplate null values and are divided and orchestrated according to the query parameters
=> [SELC-3291] Fix: getInstitutions API performs two different queries based on the parameters

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/InstitutionConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java
Set criteria subunit to null on verifyOnboarding method.
verifyOnboarding REST API checks if any onboarding on that institution has already submitted. If it happens for a parent institution, query criteria set only taxcode ignoring subunit. This behaviour is wrong because in case of parent and child, where taxcode is the same, query retrieving both. Instead, query must consider that in case of parent the subunit is null.
=> fix: verifyOnboarding adding criteria subunit is null

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/AreaOrganizzativaOmogenea.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/UnitaOrganizzativa.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java
Added call to registry proxy to retrieve an institution's city, country, county details when creating and institution from IPA
City, country, county informations are necessary for SAP for creating billing receipts. Currently these informations are not persisted on selfcare, they are retrieved from IPA only when the onboarding get's completed by loading the contract, and they are sent only by notification. Hence they don't get persisted
=> [SELC-3360] - feat: Retrieve and persist city, county, country details when creating institution from IPA

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java
Added userEventNotification service in onboarding autoApproval
So far the autoApproval only sent the onboarded institution notification to the dataLake, and no notification were sent for the users into the dedicated queue.
deployed from branch and tested by doing a manual onboarding
=> [BugFix\SELC-3385] bugfix: add send user event notification to autoOnboarding approval strategy

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
Added missing set description statement, which will allow to onboard institution properly from infocamere when using onboarding pda API
Without this set statement the institution is persisted without description field.
=> [SELC-3358] Fix: set description when creating institution from infocamere in /from-pda/ API

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyInfocamere.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
Added set origin ADE statement in CreateInstitutionStrategyInfocamere
Statement is required to persist institution with correct origin.
=> [SELC-3256] Fix: Set origin ADE when institution doesn't find data on infocamere

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
Added description to CreateInfocamereStrategyInput.
When we call API onboarding/institution to onboard pnpg institution, field description is required on Institution collection to persist institutionName in bindings objects in User collection.
=> [SELC-3256] Fix: added description for infocamere institution strategy

app/src/main/resources/swagger/api-docs-v1.json, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
Added user statuses as request parameter in API getInstitutionProducstInfo
This development was necessary to allow external api microservice, through ms-core,  to retrieve information about all onboarding linked to an user, eventually filtering by user status
I have run ms-core microservice and tested the API **/users/{id}/institution-products**
=> [SELC-3450] feat: added user states as parameter in API getInstitutionProducstInfo

app/src/main/resources/swagger/api-docs-v1.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
Remove slash for some /institutions endpoint
Some endpoints of **/institutions** contain final slash that is irrelevant for reaching the endpoints. This breaks some rest client generator so we want to remove these slashes.
=> fix: remove slash for some institutions endpoint

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/UserRegistryConnector.java, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/UserRegistryConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/UserRegistryConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java
Fix of this [PR](https://github.com/pagopa/selfcare-ms-core/pull/324).
- Persist only institution mail to pdv when it is not found on worksContract
fillUserIdAndCreateIfNotExist persist name,familyName and worksContract users using patch. Persisting name and familyName cause errors when we have to persist only institution mail. So we introduce a new method for persisting just mail to worksContract.
=> [SELC-3452] fix: persist user mail institution

app/src/main/resources/swagger/api-docs-v1.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/TokenController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java
Added new tag **external-v2** for operation that will be include into open-api for APIM
In order to avoid manual construction of open-api for APIM, all operations that will be included into this document are tagged with **external-v2** or **support**. In this way, a step of github action will scan them and automatically include into open-api.
=> [SELC-3460] feat: added tag external-v2 for automatic generation of open-api

app/src/main/resources/swagger/api-docs.json, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/input/CreateInstitutionStrategyInput.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionFromIpaPost.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionResourceMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
**Added geotaxonomy in the request for the POST /institutions/from-ipa endpoint**. This enhancement allows the association of geotaxonomy during the creation of an institution. Previously, the endpoint created an institution by retrieving data from the IPA index based on the fiscal code and subunit code, but it did not save any geotaxonomy reference entered during the onboarding phase. 
This change addresses the lack of geotaxonomy integration in the process of creating an institution through the /institutions/from-ipa endpoint. By incorporating geotaxonomy in the request, the system now aligns better with the onboarding phase requirements and ensures a more comprehensive creation of institutional data.
=> [SELC-3503] feat: enhance /institutions/from-ipa with geotaxonomy integration

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/EmailConnector.java, connector/email/src/main/java/it/pagopa/selfcare/mscore/connector/email/EmailConnectorImpl.java, connector/email/src/test/java/it/pagopa/selfcare/mscore/connector/email/EmailConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/NotificationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/NotificationServiceImplTest.java
change the implementation on email send to notify the institution of the successful onboarding.
The previous implementation used a not-certified email to notify the institutions. 
Since the institution's email is a certified email it rejects the email from selfcare. This has increased rebounce rate of the selcare email putting the aws account in review.
The new implementation uses certified aruba email that won't be rebounced by the receiver.
deployed from branch in development environment and tested by onboarding an institution, verifying that the email was correctly delivered.
=> [SELC-3679] fix: institution mail sending on PNPG domain

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/TokenConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/PaginatedToken.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/MongoCustomConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/MongoCustomConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/MongoCustomConnectorImplTest.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/TokenService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/TokenServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TokenServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/TokenController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/TokenMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/token/InstitutionToNotifyResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/token/PaginatedTokenResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/token/ScContractResponse.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/TokenControllerTest.java
**List of Changes**
- Added API to retrieve all contract to send to DataLake
**Motivation and Context**
This API has been developed in order to retrieve all contract sent on sc-contract topic
**How Has This Been Tested?**
Called api GET /tokens in TokenController in local env
=> [SELC-3693] Feat: Added API for retrieve ScContract for DL

core/src/main/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtilsTest.java
The control logic that prevents overwriting of master data that was previously performed only for PA institutions is now performed for all institutions with IPA origin. While for institutions with other origins, it is checked that the digitalAddress field has not been overwritten
It was decided to extend the check for PA institutions to all Institutions present on IPA, to prevent overwriting of certified data
Local environment
=> [SELC-1891] - feature: Changed data overwriting verification logic in onboarding api

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/UserConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/CustomError.java, connector/dao/pom.xml, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
Added api to update user binding status
an API is needed to update the status of a specific binding to satisfy the need, for example, to change the manager of an institution
Started ms locally and called new API /users/{id}/status.
=> [SELC-3700] Feat: Added api to update user binding status

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/AdditionalInformations.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/AdditionalInformationsEntity.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/AdditionalInformationsRequest.java
- change isAgentOfPublicService and isIpa to agentOfPublicService and ipa 
The mentioned fields names ("isIpa" and "isAgentOfPublicService") were not reconized.
=> [SELC-3790] fix: change field name isIpa and isAgentOfPublicService

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/OnboardingRequest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/TokenUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingResourceMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardingImportContract.java
- added activatedAt for complete onboarding 
This addition was necessary because we now have information about the date onboarding was completed
the microservice was started locally and subsequently two API calls were made from the external microservice that invoked the onboarding/complete API
=> [SELC - 3708] feat: added activatedAd for complete onboarding

app/src/main/resources/swagger/api-docs.json, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/input/CreateInstitutionStrategyInput.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionFromIpaPost.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- add institutionType in createInstitutionFromIpa method
- align api-docs
This change raises from a bug found onboarding a GPS through IPA research
When submitting a GPS onboarding, if it is present on IPA, the institution was wrongly saved as PA instead of GPS.
This change has been tested by running ms-core and ms-onboarding locally and calling API by postman.
=> [SELC-4228] fix: add institutionType in createInstitution from IPA

connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/UserRegistryConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/UserRegistryConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java
Avoid to save user mail on pdv when it is empty
In PNPG use case user mail is empty so for persist onboarding or onboarding operator methods it causes errors
=> fix: avoid save mail on pdv id empty

core/src/main/java/it/pagopa/selfcare/mscore/core/UserNotificationServiceImpl.java
- change mail subjects for users activation, sospension, reactivation and removal
This change raises to fix a bug related to email subject for users activation, sospension, reactivation and removal.
The email subject was written in english instead of italian.
This change has been tested by running core ms locally and checking notification manager logs to see the subject field.
=> [SELC-4191] fix: change mail subjects for users activation, sospension, reactivation and removal

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/TokenConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/CreatedAtRequest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Added activatedAt parameter to update activatedAt field in Token collection.
This API will be used to update the joining dates of Institutions imported from the pda. In fact, the activatedAt field has been added since it is considered as the joining date when the event is sent on the datalake.
=> [SELC-4180] feature: Added activatedAt parameter to update createdAt API.

app/src/main/resources/swagger/api-docs.json, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionOnboardingRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingResourceMapper.java
Added activatedAt to persist onboarding request for saving it as createdAd
It is needed when persist onboarding from an import
=> hotfix: save activatedAt as createdAt when persist onboarding

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
Added filter on status to get only active onboardings.
The API must recognize the only token in the Active state for the institution and product pair before attempting to update the dates
local env
=> [SELC-4180] fix: filter for ACTIVE onboarding when updating createdAt and activatedAt dates

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationRepository.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java
- modify delegations' findByToAndStatus to return a List
- align checkIfDelegationsAreActive method
This change was necessary to fix un unhandled exception when there are more than one delegation still active for an institution.
It was tested by invoking the mentioned API locally and checking the following cases:
- when there are no more delegations in status active
- when there is only one delegation in status active
- when there are more than one delegation in status active
=> fix: [SELC-4536] fix deleteDelegations query findByToAndStatus

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
When an institution needs to retrieve the delegations received, it can filter the response using some parameters such as the sender's tax code or the sender's name.
Adding taxCode param on getDelegation API.
=> [SELC-4520] Adding new taxCode param on search delegation

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java
Added condition to check if criterias are empty or not
This fix is necessary to invoke the getUserInfo API with a null institutionId
I have run the microservice locally and tested the API with path **/users/{userId}/institution-products**
=> [SELC-4598] fix: fix on optional parameter institutionId for getUserInfo

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/PartyRegistryProxyConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/CustomError.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java, connector/rest/docs/openapi/registry_proxy.json, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImpl.java, connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyCommon.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIvass.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/input/CreateInstitutionStrategyInput.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapperCustom.java
Modified createInstitutionFromIvass API to work using ivassCode instead of taxCode. In CreateInstitutionStrategyIvass now we don't check for previous persisted institution using taxCode, but we try to query using origin and originId.
In the context of foreign insurance companies onboarding, it is necessary to make it possible to create institutions using the Ivass code since the tax code is not always present.
local env
=> [SELC-4470] feat: modified createInstitutionFromIvass API to work using ivassCode instead of taxCode

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapperCustom.java
removed ivassCode parameter, instead will use originId
it's better not to use a parameter called ivassCode, because selfcare-onboarding will not be able to provide it
=> [SELC-4466] fix: removed ivassCode parameter, instead will use originId

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/PartyRegistryProxyConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/ASResource.java, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImpl.java, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/mapper/AsMapper.java, connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIvass.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
renamed AsResource class in ASResource and set originId as externalId when persisting new Institution from IVASS
=> SELC-4470 fix: renamed AsResource class in ASResource and set ExternalId as originId

app/src/main/resources/config/core-config.properties, connector-api/src/main/java/it/pagopa/selfcare/mscore/config/CoreConfig.java, core/src/main/java/it/pagopa/selfcare/mscore/core/MailNotificationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/MailNotificationServiceImplTest.java
=> fix: Avoid send PEC when application are not under NAT

app/src/main/resources/config/application.yml, app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/InstitutionToNotify.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractEventNotificationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractEventNotificationServiceImplTest.java
- add taxCodeSfe in InstitutionToNotify model
- add taxCodeSfe setting in ToInstitutionToNotify mapper
- add anotation to avoid null fields in queue message
- align open api
It's requested to persist codiceFiscaleSfe for UO to queue.
It has been tested by running locally ms-core microservice pointing to dev queue.
=> [SELC-4822] feat: add taxCodeSfe to contract queue

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/DelegationWithPagination.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/GetDelegationParameters.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/PageInfo.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2Controller.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/delegation/DelegationWithPaginationResponse.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2ControllerTest.java
- add v2 API of getDelegations with pagination
- add unit tests
- align open api
The new version of API getDelegations was required to include pagination in "I tuoi enti" dashboard FE page .
It was tested by running ms-core locally and call API getDelegationsV2.
=> [SELC-4711] feat: add v2 of API getDelegations to manage pagination

core/src/main/java/it/pagopa/selfcare/mscore/core/MailNotificationServiceImpl.java, infra/container_apps/env/dev-pnpg/terraform.tfvars, infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod-pnpg/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars
* **Correction of Environment Variable Names**: The names of the AWS-related environment variables have been fixed. The variables **AWS_SES_ACCESS_KEY_ID** and **AWS_SES_SECRET_ACCESS_KEY** were incorrectly named and have been updated to the correct names.
* **Block Sending Emails to Real Users in Dev and UAT**: To prevent real users from receiving emails in non-production environments (Dev and UAT), a block has been implemented. This ensures that any email-sending functionality checks if is enabled an alternative mail and only sends emails to test accounts in these environments.
=> hotfix: Environment Variable Names and Add Email Sending Block in Dev and UAT

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/Delegation.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/DelegationEntity.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/DelegationMapper.java
- add toTaxCode and fromTaxCode fields in delegation Entity
This change is needed to retrieve delegation taxCodes through Delegation Collection.
It was tested by running ms-core locally and calling both createDelegation and crateDelegationFromTaxCode APIs.
=> [SELC-4908] feat: add toTaxCode and fromTaxCode in delegation

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GetDelegationsMode.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/GetDelegationParameters.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2Controller.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/DelegationMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2ControllerTest.java
- remove aggregation to retrieve taxCode
- add filter taxCode in collection Delegation
- add delegation response mapper to return the appropriate taxCode
- remove mode filter
- align open api
This change is related to the addition of fields toTaxCode and fromTaxCode in collection Delegation, in this way it's possible to retrieve taxCode direclty from Delegation Collection.
It was tested by running locally both getDelegations and getDelegationsV2 APIs
=> [SELC-4910] feat: remove aggregation to retrieve taxCode field

app/src/main/resources/config/application.yml, connector/rest/pom.xml, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImpl.java
- Added the resilience4j-spring-boot2 dependency to the pom.xml 
- Configured the retry properties in the application.yml
- Added Retry annotation on getExtByCode method
- Add constant to resolve code smell
This PR introduces a retry mechanism for getExtByCode call by utilizing the resilience4j-spring-boot2 library.
This change was necessary because of sporiadic endpoint's failures.
=> [SELC-4883] feat: add retry on retrieveGeographicTaxonomies

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/DelegationType.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
- add EA (Enti Aggregatori) DelegationType
- align open api
This modification pertains to the feature of Enti Aggregatori, enabling the association of an aggregator with aggregated institutions.
It was tested by running ms locally and calling createDelegation API with field "type" set to "EA".
=> [SELC-4976] feat: add EA DelegationType

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- Refactor method createPgInstitution to return already existing institution instead of throwing ResourceConflict Exception
To prevent errors in the event of parallel institution creation requests, it is necessary to modify the flow in order to call a single API that retrieves or saves the institution via the taxCode
=> [SELC-5020] Fix: Return existing Institution if it already exists, instead of throwing ResourceConflict Exception

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- Refactor method createPgInstitution to return already existing institution instead of throwing ResourceConflict Exception
To prevent errors in the event of parallel institution creation requests, it is necessary to modify the flow in order to call a single API that retrieves or saves the institution via the taxCode
=> [SELC-5020] Fix: Return existing Institution if it already exists, instead of throwing ResourceConflict Exception 

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
- fixed filters in verify onboarding
During the current verify onboarding procedure, if a parent Institution tried to subscribe to a product that was ACTIVE on one of its UOs or AOOs, a 204 was returned and therefore it was erroneously not allowed to carry out onboarding. This happened because even if the originId was passed with the taxCode in the current code the originId was passed null and therefore the search was made only for taxCode, which shared between the parent Institution and its UO/AOOs, the body was found in the find. To solve this problem it was decided to use the subunitCode as a filter even if null is passed, in such a way as to search for the entity without that attribute so as to ignore the presence of any UO/AOOs in the find.
the verify onboarding API was invoked by …
=> [SELC - 5131] bugfix: fixed filters in verify onboarding

core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java
- remove product pagoPa condition in createDelegation
- remove and align unit tests
This change was required to move product pagoPa logic from BE to BFF.
With this modification createDelegation API on ms-core is semplied and reusable.
It was tested locally by running both ms-core and bff-dashboard locally and calling createDelegation API. on bff-dashboard.
It was tested with both product prod-pagopa and prod-io.
=> [SELC-5223] feat: remove product pagoPa condition in createDelegation

app/src/main/resources/config/application.yml, app/src/main/resources/config/core-config.properties, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GenericError.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/pecnotification/PecNotification.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/PecNotificationConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/PecNotificationRepository.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/PecNotificationEntity.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/PecNotificationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java
Added PecNotification record to persistOnboarding during the onboarding process.
To meet a regulatory requirement that mandates communication to governmental entities of the user list for the SEND and App IO products, the solution allows writing the necessary information in a Mongo collection. This enables the batch process to periodically send PEC communications to the entities, containing a link to access the list of registered users in the Area Riservata.
Junit test and local test.
=> [SELC-5169] feat : Added record PecNotification in persistOnboarding

app/src/main/resources/config/core-config.properties, connector-api/pom.xml, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/pecnotification/PecNotification.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/PecNotificationEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/PecNotificationEntityMapper.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, infra/container_apps/env/dev-pnpg/terraform.tfvars, infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod-pnpg/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars
…ble the PecNotification
Refactored and added environment variables to disable PecNotification
It was necessary to add an environment variable to allow writing to the collection, making it manageable.
The code was refactored for better performance.
Junit test and local application test
=> [SELC-5169] feat : Refactored and added environment variables to disable PecNotification
