pagopa/selfcare-ms-core

.github/workflows/pull_request_template.md
* add pull request template
* chore: pull request template
=> chore: pull template request (#85)

app/src/main/resources/config/core-config.properties, core/src/main/java/it/pagopa/selfcare/mscore/core/EmailService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/EmailServiceTest.java
fix check env DESTINATION_MAILS
=> Hotfix/destination mails (#99)

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/UserConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/GenericError.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
=> Release dev

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtilsTest.java, helm/pnpg/values.yaml, helm/values.yaml, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionPut.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/PgInstitutionPut.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/model/mapper/MigrationInstitutionMapperTest.java
removed endpoint update institution pg
normalization update institution legacy
remove duplication code that cause some bug
Try to update institution description by pnpg dashboard
=> Release dev: removed update institution pg and normalization update institution legacy

web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/ExternalControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Fix bug: when returning institution from id origin is not present
=> fix: InstitutionMapper missing map origin

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/OnboardingControllerTest.java
=> [SELC - 2472] - implemented consume token api (#120)

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
Create new filter for retrieve institutions by product
=> Add new filter

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/CreateInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/ExternalController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/ManagementController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapperCustom.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionResourceMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/RelationshipMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/TestUtils.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest2.java, web/src/test/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapperCustomTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/model/mapper/MigrationInstitutionMapperCustomTest.java
added endpoint createInstitution: POST /institutions
Needed to save institution with raw data
Call POST /institutions with Institution as body
=> feat: added endpoint createInstitution POST

core/src/main/java/it/pagopa/selfcare/mscore/core/util/UtilEnumList.java
Remove DELETED from VALID_RELATIONSHIP_STATES list so verify and complete method don't throw error if onboarding deleted exists
Permit onboarding when onboarding deleted exists
Submit onboarding when onboarding deleted exists
=> feat: permit onboarding when onboarding deleted exists

core/src/main/java/it/pagopa/selfcare/mscore/core/util/PdfMapper.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/PdfMapperTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java
1. a condition has been added that allows to populate the contract with the institution's parent name if the institution is an AOO or a UO
it was necessary to make this change to have a clearer reference in the contract having introduced the AOO and the UO
Onboardings have been performed as AOO, as UO, and as EC. In the first and second case the field in the contract was populated correctly, in the third case it was not populated
=> [SELC- 2496] - added parentDescription contract mapping for AOO and UO

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/NotificationToSend.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java
Fix Notification payload changing state to CLOSED when an onboarding is DELETED
This fix is mandatory to be compliant with Kafka payload
=> fix: Notification payload: CLOSED when onboarding state DELETED

app/src/main/resources/swagger/api-docs-v1.json, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardedInstitutionResponse.java
Mapped parent description to returned OnboardedInstitutionResource
The mapping was missing
=> Map parentDescription to OnboardedInstitutionResponse

core/src/main/java/it/pagopa/selfcare/mscore/core/EmailService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/EmailServiceTest.java
=> Merge-back from main

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/Token.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/user/UserBinding.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/UserBindingEntity.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingDaoTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/UserMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/user/InstitutionProducts.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/user/Product.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/user/UserProductsResponse.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
Added api @UserController that retrieves bindings by userId
Added institutionName and institutionRootName at users collection
Needed to expose bindings only with institution name and retrieving userId by jwt token 
Try to call GET /user/{userId}/products
=> feat: added api get products and roles by userId

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationRepository.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/exception/CustomExceptionHandler.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/delegation/DelegationResponse.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest2.java, web/src/test/java/it/pagopa/selfcare/mscore/web/exception/CustomExceptionHandlerTest.java
Added endpoint GET /institutions/{institutionId}/delegations
Added findBy institutionId and productId
[Task-SELC2639]
Needed to retrieve delegations by institutionId and productId
Try to call 
- GET /institutions/0547e98b-9a95-49e7-b0e7-d1fc38dc399f/delegations
- GET /institutions/0547e98b-9a95-49e7-b0e7-d1fc38dc399f/delegations?productId=prod-io
=> feat: added retrieve delegations by institutionId and productId

core/src/main/java/it/pagopa/selfcare/mscore/core/util/NotificationMapper.java
Added mapping to generate random id for user notification
Notification with the same id were sent for user events
=> Random id generator for notification events

CODEOWNERS
=> fix: Removing Users not @pagopa

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/InstitutionToNotify.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/RootParent.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java
The subUnitCode, subUnitType and RootParent fields have been added for sending the notification to datalake
To test the change made, an onboarding was performed in order to send a notification to datalake, subsequently it was verified that the added fields had been sent
=> [SELC - 2777] added subUnitCode, subUnitType and RootParent for DataLake

app/src/main/resources/swagger/api-docs-v1.json, web/src/main/java/it/pagopa/selfcare/mscore/web/model/delegation/DelegationResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/DelegationMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
=> [SELC - 2781] updated delegation response variable name

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserNotificationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserNotificationServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserRelationshipService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserRelationshipServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserNotificationServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserRelationshipServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/OnboardingControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
retrieve loggedUser from UserRegistry to resolve template's placeholder.
[SELC-2668]
template's placeholder were incorrectly resolved
try to activate or suspend an User and check mail.
[SELC-2668]: https://pagopa.atlassian.net/browse/SELC-2668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: get UserId to retrieve User from UserService.

app/src/main/resources/swagger/api-docs-v1.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
=> [SELC - 2781]fix: updated delegation controller variable name

web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java
Get SelfcareUser.username from principal for logged user's first name
SelfcareUser.name return userId
sent email for new user
=> fix: Get SelfcareUser.username from principal for logged user's first name

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java
Get digitalAddress from given onboardingRequest instead of institutionEntity
Before onboarding PG institutionEntity have null digitalAddress
try to onboarding PG
=> fix: send Mail to digitalAddress given in onboardingRequest

web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardedProductResponse.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/ExternalControllerTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Add OnboardedProduct List in InstitutionResponse
=> refactor: Add OnboardedProduct List in InstitutionResponse

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/NotificationToSend.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java
Ad activatedAt and deletedAt dates
Data lakes needs these informations in order to send billings to institutions that have onboarded a product
=> add activated at and deletedAt fields to the notification message

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategy.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyRaw.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/CreateInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java
Added business logic to create EC in case of AOO/UO onboarding
This development was necessary to store EC and relative relationship after AOO/UO onboarding
I have run ms-core microservice locally aiming to dev environment. After that, I have called the api **/institutions/from-ipa** and checked that after the request, AOO and EC have been created.
=> Added logic to create ec in case of onboarding AOO/UO

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java
Fix regression introduced into onboarding process for AOO/UO
This fix was necessary to avoid to process central institution twice.
=> Removed throw of resource exception

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java
=> fix: delete only ACTIVE association

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/NotificationToSend.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java
=> Add subunit data only if AOO or UO

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/SchedulerService.java
Release Production: Working on send all onboarding event to datalake
=> Release Production

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/Config.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/utils/MockUtils.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/SchedulerService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/SchedulerServiceTest.java
Adding unit test and pagination
=> Notification: Add unit test

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/ConfigEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/ConfigMapper.java, core/src/main/java/it/pagopa/selfcare/mscore/core/SchedulerService.java
=> Release prod

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/TokenMapper.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java
Changed method to set the fileName propertie in NotificationToSend mapper
tested locally and deployed from branch, called onboarding complete api and loaded a contract for a given tokenId and verified on queue that the property was correctly set
=> fix fileName set in notificationToSend

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/UserMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/user/UserResponse.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
- Add new Api for retrieve User Data
- Required new api
- call endpoint /user/{userId}?productId="productId"
=> SELC-2962 Add new Api for retrieve User Data

connector/email/src/main/java/it/pagopa/selfcare/mscore/connector/email/EmailConnectorImpl.java
=> [SELC - 3013 - fix] removed close() method and added finish() one

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java
Fix status of onboarding from DELETED to REJECTED in case of outdated request.
=> Fix status of onboarding from DELETED to REJECTED in case of outdated request

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/PdfMapper.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/PdfMapperTest.java
Fix data in input for pdf mapper in case of SA
=> Fix data in input for pdf mapper in case of SA

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/PdfMapper.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/PdfMapperTest.java
=> Fix retrieve rea, shareCapital and registerPlace for SA (#256)

app/src/main/resources/swagger/api-docs-v1.json, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java
Update status in case of PT onboarding approval from PENDING to ACTIVE
This change is necessary to avoid step of contract's signature for PT onboarding
=> Update status in case of PT onboarding approval from PENDING to ACTIVE

connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/PartyRegistryProxyConnectorImplTest.java
=> add tests to increase coverage

connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/Origin.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/PricingPlan.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/PdfMapper.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/PdfMapperTest.java
Updated pdf parameters for io contract. In particular, the logic about pricing plan binding was changed in order to fill input checkbox dinamically.
This change was necessary in order to align core logic to new contract for io product
=> Updated pdf parameters for io contract

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingDao.java
Added Optional.empty when we pass state on createUser on onboarding
When create new user a nullpointer is thrown , it causes unwanted delete user.
=> Fix nullpointer when create new user

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtilsTest.java
added if condition for institutionType PT
Like SA, a institution with institutionType PT must not expose the recipientCore, so this check was removed
Local onboarding was carried out with various institutionTypes to verify that everything is working correctly
=> [SELC -3173] added if condition for institutionType PT

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/TokenRelationships.java, core/src/main/java/it/pagopa/selfcare/mscore/core/TokenServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/TokenUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/TokenResponse.java
Added some missing fields to token relationships response
=> add new fields to tokenRelationships

helm/values-prod.yaml
=> Hotfix cors https://api.platform.pagopa.it

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/InstitutionUpdate.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/OnboardingInstitutionStrategyTest.java, pom.xml, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionUpdateRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardingInstitutionRequest.java
- added ivassCode to request for AS
- updated commons version
- added check if institution is AS to onboardingInstitution
a new type of institution must be able to onboard to SelfCare and has a new attribute called IVASS code.
it was decided that this code will be saved in a new attribute in the request and subsequently in the OriginId field of the institution collection on Mongo, as it is a unique code.
- implemented unit test
=> [SELC - 3231] feat: added ivassCode to request for AS and updated commons version

core/src/main/java/it/pagopa/selfcare/mscore/core/util/OnboardingInstitutionUtils.java
Map institutionType AS to relationship status PENDING
=> add institutionType AS to getStatusByInstitutionType

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/OnboardingUsersRequest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardingInstitutionUsersRequest.java
added sendCreateUserNotificationMail for migration
Users need to be migrated and there is no need to send the email, which is why this parameter was introduced
local onboarding user was performed
=> [SELC - addedBooleanToSendUserMail] feat: added sendCreateUserNotificationMail for migration

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/InstitutionUpdate.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/InstitutionUpdateEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/TokenMapper.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java, pom.xml, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionUpdateRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionUpdateResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapperCustom.java
Persisting city, county, country information for institutions coming from origin different than IPA,
Sending the city, county, country informations to datalake
Sap needs these infos to emit billings for institutions that has onboarded paid packages of the available products
=> [SELC-3329] feat: persist institution city, county, country informations

app/src/main/resources/swagger/api-docs-v1.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/OnboardingRequest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java, pom.xml, web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardingInstitutionRequest.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties
Added parameter in onboarding autocomplete API to prevent sending email
Needed for PDA tool
=> [SELC-3351] feat: added parameter to prevent sending email on onboarding autocomplete

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, .devops/pnpg-code-review-pipelines.yml, .devops/pnpg-deploy-pipelines.yml, Dockerfile, pom.xml
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
- updated dockerfile image
These updates are necessary as there is a need to upgrade to java 17
- Build was done locally
- the microservice was started locally and some APIs were invoked
=> [SELC-3371] feat: Update to jdk 17

helm/templates/pdb.yaml, helm/values-prod.yaml, helm/values.yaml
Add PDB definition to Helm Chart
In order to upgrade the cluster, we need to set the PDB to ensure no downtime while moving pods across nodes
=> Add pdb to helm chart

helm/templates/pdb.yaml, helm/values-prod.yaml
Fix formatting thing
Disable PDB for PROD
Want to avoid any accidental deploy in prod of the PDB, since the PROD cluster's service account doesn't have permissions yet
=> Disable PDB for UAT and PROD envs

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/InstitutionToNotify.java, core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java
…present
Added category field to datalake notification model
Datalake needs to identify the PAC/PAL information relative to the onboarding contract, and needs the institution's category to sort the information out
=> [SELC-3413] feat: add  category field to notification to datalake

helm/templates/pdb.yaml, helm/values-prod.yaml, helm/values.yaml
=> Update values.yaml removing pbd

helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml
Set host on Kubernetes ingress
Wildcard would not work anymore when cluster will be upgraded to a newer version
=> [SELC-3341] Set host on ingress (PROD)

core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java
Retreive categories from registry proxy if not present on institution saved in selfcare
=> [SELC-3263] feat: resend onboarding notification to DL with category retrieval

core/src/main/java/it/pagopa/selfcare/mscore/core/ContractService.java, core/src/test/java/it/pagopa/selfcare/mscore/core/ContractServiceTest.java
changed cathegory setting logic inside notification build method in contract service
=> fix notification city, country, county setting logic

app/src/main/resources/swagger/api-docs.json, app/src/test/java/it/pagopa/selfcare/mscore/web/config/SwaggerConfigTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionOnboardingRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionResourceMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingResourceMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
* Added a new POST REST API to the Institution Controller.
* This API is responsible for saving the association between an institution and a product.
* It also creates occurrences in the Users collection as part of this process.
This change was necessary to complete the onboarding process in the domain of Onboarding. This POST API facilitates the creation of an institution and the association of the same with a product in an ACTIVE state.
=> [SELC-3452] feat: post API persist onboarding

web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapperTest.java
Added check if institution.onboarding is not null
Nullpointer happens for some users when onboarding is null. It must skip the method in this case.
=> fix: check if institution.onboarding exists

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/UserConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/UserServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
Refactor for API getInstitutionProducts
This change was necessary to reduce computation complexity of previous method.
I have run ms-core locally aiming to dev environment.
=> [SELC-3553] feat: Refactor api getInstitutionProducts

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingResourceMapper.java
* Added set institution type PA when create from IPA
* Fix mapper contract path on persist onboarding
=> fix: institution type from ipa and mapper contract path

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/UserConnectorImpl.java
Fix filter on aggregation for getUserInfo
This fix prevents null pointer exception in case of aggregation with an empty node for institution.
I have run microservice ms-core locally aiming to UAT environment (database)
=> Fix filter on aggregation for getUserInfo

helm/values-prod.yaml
Enable PDB to max 1 unavailable
Increase to 3 replicas
No downtime update
=> [SELC-3584] Enable PDB - PROD

helm/values-prod.yaml
Increase min available pdb policy
Having 3 replicas, it'd better to have at least 2 pods always running
=> [SELC-3584] Increase minAvailable PDB policy - PROD

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java
- remove check on recipientCode for prod-interop
for prod-interop recipient code is not required, so we don't received it from FE
-local env
=> [SELC-3501] feat: remove check on recipientCode for prod-interop

core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/factory/OnboardingInstitutionStrategyFactory.java
**List of Changes**
remove check on recipientCode for prod-interop
**Motivation and Context**
for prod-interop recipient code is not required, so we don't received it from FE
**How Has This Been Tested?**
-local env
=> [SELC-3501] add check on productId for checkRecipientCode var

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/onboarding/TokenRelationships.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/TokenUtils.java
Added institutionUpdate in TokenRelationships model for getToken by Id API
We need to retrieve the institution update to populate the onboarding request approval form
Called API /tokens/{tokenId} with local env
=> [SELC-3694] Feat:  Add institutionUpdate in TokenRelationships model for getToken by Id API

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/AdditionalInformations.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/InstitutionUpdate.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/AdditionalInformationsEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/InstitutionUpdateEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/InstitutionMapper.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/TokenMapper.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/AdditionalInformationsRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionUpdateRequest.java
…nformations validation
- add AdditionalInformations in InstitutionUpdate
- add validateAdditionalInformations to check that all AdditionalInformations fields are correctly populated
- add unit tests
This change is related to the new onboarding needs for GPS.
During the onboarding process new informations will be collected and storaged in the AdditionalInformations object.
This information will be transmitted to the PagoPA Admin to speed up the verification phase of the institution.
=> [SELC-3791] feat: add AdditionalInformations in InstitutionUpdate

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/AdditionalInformations.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/InstitutionUpdate.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/AdditionalInformationsEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/InstitutionUpdateEntity.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/InstitutionMapper.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/TokenMapper.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java, pom.xml, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/AdditionalInformationsRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionUpdateRequest.java
=> Release UAT

connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/InstitutionMapper.java
- fix AdditionalInformationsMapper for agentOfPublicService field
=> [SELC-3791] fix: modify AdditionalInformations mapper

core/src/main/java/it/pagopa/selfcare/mscore/core/util/TokenUtils.java
- modify activatedAt setting in toToken mapper
=> [SELC-3798] fix: modify activatedAt setting in toToken mapper

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/UserController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/UserMapper.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/user/UserNotificationBindingsResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/user/UsersNotificationResponse.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/UserControllerTest.java
=> Refactor response for getAllUser

core/src/main/java/it/pagopa/selfcare/mscore/core/util/NotificationMapper.java
=> Add default value to updatedAt on user notification

core/src/main/java/it/pagopa/selfcare/mscore/core/UserEventServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserEventServiceTest.java
=> Add compliant info for user event update notification

core/src/main/java/it/pagopa/selfcare/mscore/core/UserEventServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/UserEventServiceTest.java
Bug fixing for notification event message. 
Now only one method can send message on kafka queue with schema compiant to https://pagopa.atlassian.net/wiki/spaces/SCP/pages/779747636/SC-Users. 
Fix source for createdDate and updatedDate from onboardedProduct.
=> [SELC-4060] fix: Notification event compliant to avro schema

.dockerignore, .github/workflows/call_code_review.yml, .github/workflows/pr_ms.yml, Dockerfile, Dockerfile.old, pom.xml
Add PR workflow
Refactor Dockerfile
Moving to container apps
=> [EC-150] Add PR GitHub pipeline

.github/workflows/call_release_ms.yml, .github/workflows/pr_ms.yml, .github/workflows/release_ms.yml, .github/workflows/release_ms_pnpg.yml
=> [EC-150] Misc minor changes for GitHub workflows

connector-api/src/main/java/it/pagopa/selfcare/mscore/api/TokenConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/TokenConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/CreatedAtRequest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
=> feature: Added activatedAt field to the updateCreatedAt  API.

app/src/main/java/it/pagopa/selfcare/mscore/SelfCareCoreApplication.java, core/src/main/java/it/pagopa/selfcare/mscore/core/QueueNotificationServiceImpl.java
Add async behaviour on queue notification api
=> Add async to notification api

core/src/main/java/it/pagopa/selfcare/mscore/core/QueueNotificationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/QueueNotificationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/QueueNotificationServiceTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/QueueNotificationController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/QueueNotificationControllerTest.java
Added endpoint to send contract by institutionId and tokenId
Sometimes it is needed to recover from bug on data, it is useful to have an endpoint to send a specific onboarding
=> [SELC-4419] fix : send contract by institutionId and tokenId

app/src/main/resources/swagger/api-docs.json, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
Adding test and fix skip and limit for mongo aggregation
=> fix: Add edge case to pagination params

core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/OnboardingControllerTest.java
Removed verify token on onboarding operators and added verify onboarding
On new onboarding flow token collection is not used anymore. It is needed to verify is an onboarding is ACTIVE only using onboardings list.
=> [SELC-4438] fix: verify onboarding replace verify token

core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java
Update unit tests to restore coverage at target
=> Update unit tests to restore coverage at target

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/ManagementController.java
Deprecated resource is used by external api backend
=> hotfix: added GET relationships deprecated

.github/workflows/release_ms.yml, .github/workflows/release_ms_pnpg.yml, infra/container_apps/env/dev-pnpg/terraform.tfvars, infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod-pnpg/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars, infra/container_apps/variables.tf
JWT_TOKEN_PUBLIC_KEY misses as env variable
=> [EC-119] fix: added JWT_TOKEN_PUBLIC_KEY as secret

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/main/resources/swagger/swagger_it.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
Add new text param to filter Institutions by description
=> Search delegates

web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java
If product role misses dashboard backend broke retrive authorities
=> hotfix: added default product role on onboardingInfo

core/src/main/java/it/pagopa/selfcare/mscore/core/UserEventServiceImpl.java, core/src/main/java/it/pagopa/selfcare/mscore/core/util/UserNotificationMapper.java
Add a check to evaluate null value in the workContacts field from PDV
If PDV does not contain email in workContacts object, Selfcare cretes an exception and interrupts the business activity.
=> [SELC-4609] Fix workContacts null

.github/workflows/release_open_api.yml
Change branch_ref to main for Swagger Detect Conflict and Update pipeline
=> chore: Swagger Detect trigger on main

web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/OnboardingMapper.java
Removed temporary hotfix for default product role
=> [SELC-4566] fix: removed temporary hotfix for default product role

infra/container_apps/env/dev-pnpg/terraform.tfvars, infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod-pnpg/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars, infra/container_apps/main.tf, infra/container_apps/variables.tf
Migration to Container App DEV supporting a workload profile
=> chore: Workload profiles migration DEV

infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars, infra/container_apps/locals.tf, infra/container_apps/main.tf, infra/container_apps/variables.tf
Using terraform ca module with suffix
Change cae url uat
Migration uat env with -001 suffix
=> chore: Migration uat using terraform ca module with suffix

connector/rest/src/main/resources/config/user-rest-client.properties
UserApiRestClient property file was erroneously removed
=> [SELC-4479] fix: add missing user-rest-client.properties file

infra/container_apps/env/dev-pnpg/terraform.tfvars, infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod-pnpg/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat-pnpg/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars
=> hotfix: add missing environment variables for userApiRestClients

web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/OnboardingController.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionRequest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/OnboardingControllerTest.java
Removed contraints about taxCode and vatNumber for request objects
This changes are necessary to allow onboarding for institution with empty taxCode and vatNumber
=> [SELC-4642] feat: removed contraints about taxCode and vatNumber for request objects

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/mscore/api/DelegationConnector.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/constant/Order.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java, infra/container_apps/.terraform.lock.hcl, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
Adding new order param to getDelegation API and on findDelegation.
New Order [NONE, ASC, DESC] param can help to return delegation ordered by institutionFrom description name.
=> [SELC-4717] Add order param to getDelegation

app/src/main/resources/config/core-config.properties, connector-api/src/main/java/it/pagopa/selfcare/mscore/config/CoreConfig.java, core/src/main/java/it/pagopa/selfcare/mscore/core/MailNotificationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/MailNotificationServiceImplTest.java
=> fix: Avoid send PEC when application are not under NAT

core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
Remove verification on user is associated with institution when update it
Verification moved to dashboard backend
=> hotfix: remove check user when update institution

app/src/main/resources/swagger/api-docs.json, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java
=> [SELC-4761] BUG fix: Institution aggregation now show taxcode and institution type

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/BrokerResponse.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/BrokerMapper.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- Refactor getInstitutionBrokers API to add taxCode in brokerResponse 
Broker Resource must have also institution taxCode
=> [SELC-4864] feat: Refactor getInstitutionBrokers API  to add taxCode in brokerResponse

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/UnitaOrganizzativa.java, connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java, connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/model/registryproxy/UoResponse.java, core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java, core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java, core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java
- Added taxCodeSfe in Institution for UO
We need to persist codiceFiscaleSfe for UO in Institution entity
=> [SELC-4819] Feat:  added taxCodeSfe in Institution for UO

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
added istatCode in InstitutionResponse
istatCode field is needed to build event object of SC-Contracts in selfcare-onboarding
=> [SELC-4993] feat: added istatCode in InstitutionResponse

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2Controller.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/QueueNotificationController.java
Align tags for implementation of this [RFC](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/edit-v2/1084883169)
=> [SELC-5044] chore: remove tag external-v2 and support from /v2/delegations

infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars
- set env CORE_USER_EVENT_SERVICE_TYPE to ignore
In order to remove sendToDataLake method from ms-core, at first, we'll disable event sending and then remove all methods for this task
=> [SELC-4943] Feat: set env CORE_USER_EVENT_SERVICE_TYPE to ignore

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
- add support-pnpg tag to getInstitutions
- align openapi
Align tags for implementation of this [RFC](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/edit-v2/1084883169)
=> [SELC-5093] chore: add support-pnpg tag to getInstitutions

infra/container_apps/env/dev/terraform.tfvars, infra/container_apps/env/prod/terraform.tfvars, infra/container_apps/env/uat/terraform.tfvars
This logic moved to onboarding functions
=> [SELC-4943] Feat: set env CORE_CONTRACT_EVENT_SERVICE_TYPE to ignore

.github/workflows/pr_ms.yml
=> chore: code review starts on release pr

connector-api/pom.xml, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
- updated sdk version
- cherry-pick ba040a80137fa774192ac1ef741ec1e6a6343219
=> [SELC - 5131] cherry-pick of release 1.1.5

app/src/main/resources/swagger/api-docs.json, connector-api/pom.xml, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingService.java, core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java, web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Persist onboarding status 200 when it exists
Testing with junit
=> [SELC-5192] Feat: Persist onboarding status 200 when it exists

core/src/main/java/it/pagopa/selfcare/mscore/core/DelegationServiceImpl.java, core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java
- add condition to send mail creating a delegation just when delegation type is PT
- add unit test
This change was required to avoid sending delegations mail during aggregators flow.
=> [SELC-5242] feat: add condition to sendMailForDelegation

connector-api/src/main/java/it/pagopa/selfcare/mscore/model/pecnotification/PecNotification.java, connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/PecNotificationEntity.java
Changed type of id field to Object
Junit test and application test
=> [SELC-5168] feat : changed type of id field to Object

app/src/main/resources/swagger/api-docs.json, infra/container_apps/env/dev/terraform.tfvars, web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
=> chore: Move to Container App Env workload DEV
